version: '3.5'
services:
 zookeeper-1:
    image: confluentinc/cp-zookeeper:5.5.4
    container_name: zk-1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888
      ZOOKEEPER_TICK_TIME: 2000
      #ZOOKEEPER_INIT_LIMIT: 10
      #ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_CLIENT_PORT: 2181

 #####  kafka brokers ######

 broker-1:
    image: confluentinc/cp-kafka:5.5.4
    container_name: bk-1
    depends_on:
      - zookeeper-1
    ports:
     - "9092:9092"
    expose:
     - "29092"
    environment:
      KAFKA_BROKER_ID: 1

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-1:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_ADVERTISED_HOST_NAME: broker-1
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_NUM_PARTITION: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 30000
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181'
      KAFKA_ZOOKEEPER_CONNECT_TIMEOUT_MS: 6000
      KAFKA_AUTO_CREATE_TOPIC_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=WARN,kafka.foo.bar:DEBUG'
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR

    volumes:
    - ./data/broker-1:/var/lib/kafka/data
    - ./config/broker-1:/etc/kafka

 broker-2:
    image: confluentinc/cp-kafka:5.5.4
    container_name: bk-2
    depends_on:
      - zookeeper-1

    ports:
      - "9093:9093"
    expose:
     - "29093"
    environment:
      KAFKA_BROKER_ID: 2

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-2:29093,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29093,EXTERNAL://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_ADVERTISED_HOST_NAME: broker-2
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_NUM_PARTITION: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 30000
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181'
      KAFKA_ZOOKEEPER_CONNECT_TIMEOUT_MS: 6000
      KAFKA_AUTO_CREATE_TOPIC_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=WARN,kafka.foo.bar:DEBUG'
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR

    volumes:
    - ./data/broker-2:/var/lib/kafka/data
    - ./config/broker-2:/etc/kafka

 broker-3:
    image: confluentinc/cp-kafka:5.5.4
    container_name: bk-3
    depends_on:
      - zookeeper-1

    ports:
      - "9094:9094"
    expose:
     - "29094"
    environment:
      KAFKA_BROKER_ID: 3

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-3:29094,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29094,EXTERNAL://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_ADVERTISED_HOST_NAME: broker-3
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_NUM_PARTITION: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 30000
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181'
      KAFKA_ZOOKEEPER_CONNECT_TIMEOUT_MS: 6000
      KAFKA_AUTO_CREATE_TOPIC_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=WARN,kafka.foo.bar:DEBUG'
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR

    volumes:
    - ./data/broker-3:/var/lib/kafka/data
    - ./config/broker-3:/etc/kafka
